name: LLM Code Review

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "*.md"
      - "docs/**"

jobs:
  review:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run LLM Reviewer
        uses: Omar-Sa03/llm-code-reviewer@v1
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
